### ISSUE TITLE
AES Streaming Mode

### ISSUE THREAD

**Issue by nginnever** [storj/storj-crypto#2]
Due to the lack of a streaming mode for AES ciphers in webcrypto we must fallback on a pure js implementation of ciphers. This is slow so this thread is to help track developments on a faster method of encrypting/decrypting in the browser.

ref: libp2p/js-libp2p-crypto#29 (comment)

**Comment by retrohacker** [comment]
:astonished:

**Comment by retrohacker** [comment]
:astonished: streaming is like... a big part of AES... no? Seems like a massive oversight from the implementors of WebCrypto.

**Comment by nginnever** [comment]
Since some algorithms can't support streams they have for now decided that they wont support any algorithms that can and will revisit. 

Main thread to follow: https://github.com/w3c/webcrypto/issues/73

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
